apiVersion: apps/v1
kind: Deployment
metadata:
  name: dms-swordphish3-deployment
  labels:
    app: dms-swordphish3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dms-swordphish3
  template:
    metadata:
      labels:
        app: dms-swordphish3
    spec:
      containers:
      - name: swordphish3
        image: DOCKER_IMAGE
        volumeMounts:
        - mountPath: /config
          name: config
        resources:
          limits:
            cpu: 400m
          requests:
            cpu: 200m
      - envFrom:
        - configMapRef:
          name: dtp-swordphish3-configmap
      imagePullSecrets:
      - name: registrymsprod
      volumes:
      - name: config
        configMap:
          name: dtp-swordphish3-configmap-2
          items:
            - key: logging.yml
              path: logging.yml
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - dms-swordphish-v3
              topologyKey: "kubernetes.io/hostname"
